# Use Node.js 20 with Debian Slim (includes glibc for onnxruntime-node compatibility)
FROM node:20-slim AS base

# Install dependencies only when needed
FROM base AS deps
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Exclude problematic directories
RUN rm -rf "Landing-Design" "Chatbot Design" "esfera 3d" || true

# Accept build arguments for NEXT_PUBLIC_* variables
# These MUST be passed during docker build for them to be available during Next.js build
ARG NEXT_PUBLIC_SUPABASE_URL=""
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY=""
ARG NEXT_PUBLIC_APP_URL=""
ARG NEXT_PUBLIC_SITE_URL=""
ARG NEXT_PUBLIC_BILLING_ENABLED=""
ARG NEXT_PUBLIC_WOMPI_PUBLIC_KEY=""
ARG NEXT_PUBLIC_WOMPI_BASE_URL=""

# Accept server-side environment variables (needed during build for API routes)
ARG SUPABASE_SERVICE_ROLE_KEY=""
ARG WOMPI_PRIVATE_KEY=""
ARG WOMPI_INTEGRITY_SECRET=""
ARG WOMPI_WEBHOOK_SECRET=""
ARG OPENROUTER_API_KEY=""
ARG OPENAI_API_KEY=""
ARG FIRECRAWL_API_KEY=""
ARG SERPER_API_KEY=""
ARG ADMIN_EMAILS=""
ARG ADMIN_PASSWORD=""

# Set public env vars for the build process
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_BILLING_ENABLED=$NEXT_PUBLIC_BILLING_ENABLED
ENV NEXT_PUBLIC_WOMPI_PUBLIC_KEY=$NEXT_PUBLIC_WOMPI_PUBLIC_KEY
ENV NEXT_PUBLIC_WOMPI_BASE_URL=$NEXT_PUBLIC_WOMPI_BASE_URL

# Set server-side env vars for the build process
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV WOMPI_PRIVATE_KEY=$WOMPI_PRIVATE_KEY
ENV WOMPI_INTEGRITY_SECRET=$WOMPI_INTEGRITY_SECRET
ENV WOMPI_WEBHOOK_SECRET=$WOMPI_WEBHOOK_SECRET
ENV OPENROUTER_API_KEY=$OPENROUTER_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV FIRECRAWL_API_KEY=$FIRECRAWL_API_KEY
ENV SERPER_API_KEY=$SERPER_API_KEY
ENV ADMIN_EMAILS=$ADMIN_EMAILS
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD

# Build the application
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Accept build arguments for runtime (Dokploy will override these)
ARG NEXT_PUBLIC_SUPABASE_URL=""
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY=""
ARG NEXT_PUBLIC_APP_URL=""
ARG NEXT_PUBLIC_SITE_URL=""
ARG NEXT_PUBLIC_BILLING_ENABLED=""
ARG NEXT_PUBLIC_WOMPI_PUBLIC_KEY=""
ARG NEXT_PUBLIC_WOMPI_BASE_URL=""

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_BILLING_ENABLED=$NEXT_PUBLIC_BILLING_ENABLED
ENV NEXT_PUBLIC_WOMPI_PUBLIC_KEY=$NEXT_PUBLIC_WOMPI_PUBLIC_KEY
ENV NEXT_PUBLIC_WOMPI_BASE_URL=$NEXT_PUBLIC_WOMPI_BASE_URL

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Set correct permissions
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "start"]
